sudo: false
language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

cache: .cache

before_install:
  - export CACHEDIR=$PWD/.cache/$(sha256sum .travis.yml .travis/* | sha256sum | cut -f1 -d' ')
  - export SRCDIR=$CACHEDIR/src
  - export PREFIX=$CACHEDIR/usr
  - mkdir -p $SRCDIR $PREFIX/{bin,lib}
  - export PATH=$PREFIX/bin:$PATH

install:
  - .travis/install_protobuf.sh
  - pip install -r requirements.txt
script:
  - nosetests
